version: '3.8'

services:

  besu:
    image: hyperledger/besu:latest
    container_name: besu-node
    ports:
      - "8545:8545"
    command:
      - --network=dev
      - --rpc-http-enabled
      - --rpc-http-host=0.0.0.0
      - --rpc-http-api=ETH,NET,WEB3
      - --host-allowlist=*
      - --rpc-http-cors-origins=all

  postgres:
    image: postgres:16
    container_name: audit-postgres
    environment:
      POSTGRES_DB: audit_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"